language: rust
cache: cargo
dist: xenial
sudo: true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    - libiberty-dev
    - zlib1g-dev

# Run builds in Linux, MacOS X and Windows
os:
- linux
- osx
- windows

# Run builds for all the supported trains
rust:
- 1.32.0
- 1.33.0
- 1.34.2
- stable
- beta
- nightly

stages:
- test
- deploy

# Check multiple features
env:
- DEFAULT_FEATURES=true
- DEFAULT_FEATURES=true FEATURES="no_std"
- DEFAULT_FEATURES=false
- DEFAULT_FEATURES=false FEATURES="no_std"

# Extra jobs to include
jobs:
  include:
  # Upload documentation
  - name: "Documentation upload"
    os: linux
    rust: stable
    stage: deploy
    env: CACHE_NAME=DOCS
    script: ./travis-helper.sh documentation
    deploy: &pages
      provider: pages
      github-token: $GH_TOKEN
      local-dir: target/doc/
      skip_cleanup: true
      keep-history: true
      on:
        repo: Razican/vsop87-rs
        branch: develop
  # Crates.io deployment
  - name: "crates.io deployment"
    os: linux
    rust: stable
    stage: deploy
    env: CACHE_NAME=DEPLOY
    script: skip
    deploy:
      provider: cargo
      token: $CARGO_TOKEN
      on:
        repo: Razican/vsop87-rs
        tags: true

matrix:
  allow_failures:
  - os: windows

# Run the multiple tests.
script:
- ./travis-helper.sh fmt_check
- ./travis-helper.sh clippy_check
- ./travis-helper.sh test

# Upload code coverage report
after_success:
- ./travis-helper.sh upload_code_coverage
