language: rust
sudo: false
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

# run builds for all the trains
rust:
  - nightly
  - beta
  - stable
  - 1.7.0
  - 1.6.0
  - 1.5.0
  - 1.4.0
  - 1.3.0
  - 1.2.0
  - 1.1.0
  - 1.0.0

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# the main build
script:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc;
      fi
  - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cargo build -v &&
      cargo test &&
      cargo bench;
      fi
after_success:
  - |
      if [["$TRAVIS_OS_NAME" == "linux"]]; then
      travis-cargo --only stable doc-upload;
      fi
  - |
      if [["$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable"]]; then
      travis-cargo coveralls --no-sudo --verify;
      fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
