language: rust
cache: cargo
dist: focal

# Run builds in Linux, MacOS X and Windows
os:
- linux
- osx
- windows

arch:
- amd64
- arm64

# Run builds for all the supported trains
rust:
- 1.36.0
- stable
- beta
- nightly

stages:
- test
- deploy

# Check multiple features
env:
- DEFAULT_FEATURES=true
- DEFAULT_FEATURES=true FEATURES="no_std"
- DEFAULT_FEATURES=false
- DEFAULT_FEATURES=false FEATURES="no_std"

# Extra jobs to include
jobs:
  allow_failures:
  - os: windows
  include:
  # Upload documentation
  - name: "Documentation upload"
    os: linux
    rust: stable
    stage: deploy
    env: CACHE_NAME=DOCS
    script: ./travis-helper.sh documentation
    deploy: &pages
      provider: pages
      token: $GH_TOKEN
      local_dir: target/doc/
      cleanup: true
      keep_history: true
      strategy: git
      on:
        repo: Razican/vsop87-rs
        branch: develop
  # Crates.io deployment
  - name: "crates.io deployment"
    os: linux
    rust: stable
    stage: deploy
    env: CACHE_NAME=DEPLOY
    script: skip
    deploy:
      provider: cargo
      token: $CARGO_TOKEN
      on:
        repo: Razican/vsop87-rs
        tags: true

# Run the multiple tests.
script:
- ./travis-helper.sh fmt_check
- ./travis-helper.sh clippy_check
- ./travis-helper.sh test

# Upload code coverage report
after_success:
- ./travis-helper.sh upload_code_coverage
