[package]
name = "vsop87"
version = "0.4.0-dev"
authors = ["Razican <admin@razican.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/Razican/vsop87-rs"
documentation = "http://razican.github.io/vsop87-rs"
description = """
VSOP87 Rust implementation. Includes VSOP87, VSOP87A, VSOP87B and VSOP87C versions. The rest of the
versions (VSOP87D and VSOP87E) will be implemented in the future.
"""
keywords = ["vsop87", "simulation", "astrophysics", "astronomy"]
