[package]
name = "vsop87"
version = "0.2.0-dev"
authors = ["Razican <admin@razican.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/Razican/vsop87-rs"
description = """
VSOP87 Rust implementation
"""
keywords = ["vsop87", "simulation", "astrophysics", "astronomy"]
