[package]
name = "vsop87"
version = "2.0.0"
authors = ["Iban Eguia <razican@protonmail.ch>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/Razican/vsop87-rs"
documentation = "https://docs.rs/vsop87/"
description = """
Pure Rust VSOP87 algorithm implementation. Includes all VSOP87 algorith versions:
VSOP87, VSOP87A, VSOP87B, VSOP87C, VSOP87D and VSOP87E.

VSOP87 are a family of algorithms used to predict the position of planets in the
solar system with great accuracy. That position can be used by astronomical
software to create views of the sky, or by simulation software to know the
position of the planets.
"""
keywords = ["vsop87", "simulation", "astrophysics", "astronomy"]
categories = ["science"]

[dev-dependencies]
rand = "0.3.15"
