[package]
name = "vsop87"
version = "1.1.0-dev"
authors = ["Razican <admin@razican.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/Razican/vsop87-rs"
documentation = "http://razican.github.io/vsop87-rs"
description = """
VSOP87 Rust implementation. Includes all VSOP87 algorith versions: VSOP87, VSOP87A, VSOP87B,
VSOP87C, VSOP87D and VSOP87E.
"""
keywords = ["vsop87", "simulation", "astrophysics", "astronomy"]
