[package]
name = "vsop87"
version = "0.5.1"
authors = ["Razican <admin@razican.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/Razican/vsop87-rs"
documentation = "http://razican.github.io/vsop87-rs"
description = """
VSOP87 Rust implementation. Includes VSOP87, VSOP87A, VSOP87B, VSOP87C and VSOP87D versions. The
VSOP87E version will be implemented in the future.
"""
keywords = ["vsop87", "simulation", "astrophysics", "astronomy"]
